### ISSUE TITLE
Instance Method not working in ActiveRecord[6.0]

### ISSUE THREAD

**Issue by farah-pdtech** [ClosureTree/closure_tree#353]
mostly instance method not working and show error

NoMethodError: undefined method `children' for # <ModelName::ActiveRecord_Relation:0x00007fd87f291fd0>

only few of it that works, such as -> root, hash tree

is there any solution for this?
